### ISSUE TITLE
Bu Mükellef Kullanıcı Bilgilerini Güncellemedi

### ISSUE THREAD

**Issue by blackhawktr** [furkankadioglu/efatura#100]
Merhaba,
Sanırım bugün GİB'te güncelleme olmuş. Şahıs firmalarında ad soyad bilgileri silinmiş. e-Arşiv portalda Bu Mükellef Kullanıcı Bilgilerini Güncellemedi hatası vermeye başladı fakat Ad Soyad bilgilerini tekrar doldurunca sorun düzeldi. Ama kütüphane hala aynı hatayı veriyor. Kütüphanenin de güncellenmesi mi gerekli yoksa kendiliğinden düzelir mi sizce?
Konu hakkında bilgisi olan paylaşabilirse sevinirim.
Sayın @furkankadioglu Bey veya Sayın @muratcesmecioglu Bey in de desteklerini rica ederim.

**Comment by muglali20** [comment]
MErhaba;
Evet Test Ortamında Fatura Oluşturuyor ama Canlı Ortamda 
  Uncaught furkankadioglu\eFatura\Exceptions\ApiException: Sunucu taraflı bir hata oluştu!

hatasını veriyor bu konuda 
Sayın @furkankadioglu Bey veya Sayın @muratcesmecioglu Bey  Bakabilir Misiniz

**Comment by erenn44** [comment]
Aynı hatayı almaktayım çözebilen oldu mu?

**Comment by blackhawktr** [comment]
İkinizde de sorun aynı dimi arkadaşlar?
GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?

**Comment by muglali20** [comment]
> İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?

Hata Olarak Bilgi Boş Değil Fatura Oluşturulamadı Olarak hata Dönüyor Test Ortamında Sorun yok lakin GIB Güncelleme Sonra Canlı Ortamda Fatura Oluşturamıyoruz Çözum Bulan varsa Payalaşablir mı?

**Comment by blackhawktr** [comment]
> > İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?
> 
> Hata Olarak Bilgi Boş Değil Fatura Oluşturulamadı Olarak hata Dönüyor Test Ortamında Sorun yok lakin GIB Güncelleme Sonra Canlı Ortamda Fatura Oluşturamıyoruz Çözum Bulan varsa Payalaşablir mı?

InvoiceManager.php deki createDraftBasicInvoice fonksiyonunda
```
if ($body["data"] != "Faturanız başarıyla oluşturulmuştur. Düzenlenen Belgeler menüsünden faturanıza ulaşabilirsiniz.") {
            throw new ApiException(json_encode($body['data']), 0, null, $body);
}
```
Değişikliğini yaparsanız hatanın sebebini ekrana basar. Muhtemelen sizde de Mükellef bilgilerini güncellemedi hatası verecek.

**Comment by erenn44** [comment]
> İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?

evet aynen bu hatayı almaktayız.

**Comment by erenn44** [comment]
> > > İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?
> > 
> > 
> > Hata Olarak Bilgi Boş Değil Fatura Oluşturulamadı Olarak hata Dönüyor Test Ortamında Sorun yok lakin GIB Güncelleme Sonra Canlı Ortamda Fatura Oluşturamıyoruz Çözum Bulan varsa Payalaşablir mı?
> 
> InvoiceManager.php deki createDraftBasicInvoice fonksiyonunda
> 
> ```
> if ($body["data"] != "Faturanız başarıyla oluşturulmuştur. Düzenlenen Belgeler menüsünden faturanıza ulaşabilirsiniz.") {
>             throw new ApiException(json_encode($body['data']), 0, null, $body);
> }
> ```
> 
> Değişikliğini yaparsanız hatanın sebebini ekrana basar. Muhtemelen sizde de Mükellef bilgilerini güncellemedi hatası verecek.

Bende direkt kullanıcı bilgileri güncellenmedi diyor normal e-arşiv e girip güncelleyip oradan kesince sıkıntı yok ama tekrar kütüphaneden girince kesmiyor ve aynı hatayı veriyor hata aldıktan sonra tekrar e-arşiv portaldende kesmeyip tekrar güncelleme yapınca kesiyor portal üzerinden

**Comment by muglali20** [comment]
Fatal error: Uncaught furkankadioglu\eFatura\Exceptions\ApiException: Fatura oluşturulamadı. in /home/**/public_html/vendor/furkankadioglu/efatura/src/InvoiceManager.php:495 Stack
Şeklinde Hata veriyor

**Comment by blackhawktr** [comment]
> > > > İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalde Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullanırken başlıktaki hatayı alıyorsunuz?
> > > 
> > > 
> > > Hata Olarak Bilgi Boş Değil Fatura Oluşturulamadı Olarak hata Dönüyor Test Ortamında Sorun yok lakin GIB Güncelleme Sonra Canlı Ortamda Fatura Oluşturamıyoruz Çözum Bulan varsa Payalaşablir mı?
> > 
> > 
> > InvoiceManager.php deki createDraftBasicInvoice fonksiyonunda
> > ```
> > if ($body["data"] != "Faturanız başarıyla oluşturulmuştur. Düzenlenen Belgeler menüsünden faturanıza ulaşabilirsiniz.") {
> >             throw new ApiException(json_encode($body['data']), 0, null, $body);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Değişikliğini yaparsanız hatanın sebebini ekrana basar. Muhtemelen sizde de Mükellef bilgilerini güncellemedi hatası verecek.
> 
> Bende direkt kullanıcı bilgileri güncellenmedi diyor normal e-arşiv e girip güncelleyip oradan kesince sıkıntı yok ama tekrar kütüphaneden girince kesmiyor ve aynı hatayı veriyor hata aldıktan sonra tekrar e-arşiv portaldende kesmeyip tekrar güncelleme yapınca kesiyor portal üzerinden

Hocam bu kısmı anlamadım.
e-Arşive girip güncelliyorsunuz ordan kesebiliyorsunuz.
Sonra tekrar kütüphaneden girip deniyorsunuz hata veriyor. --> Buraya kadar tamam.
Sonra tekrar E-Arşiv portalden kesmek için 2. defa güncelleme yapmanız mı gerekli?

Böyleyse kütüphena e-arşivdeki bilgileri sıfırlıyor o zaman?

**Comment by muglali20** [comment]
Evet

> > > > > İkinizde de sorun aynı dimi arkadaşlar? GİB e-Arşiv Portalında Adınız Soyadınız GİB güncellemesinden sonra silindi. Tekrar doldurmanıza rağmen bu kütüphaneyi kullandığınız başlıktaki yanlışları bilmiyor musunuz?
> > > > 
> > > > 
> > > > Hata Olarak Bilgi Boş Değil Fatura Oluşturamadı Olarak hata Dönüyor Test Ortamında Sorun yok lakin GIB Güncelleme Sonrası Canlı Ortamda Fatura Oluşturamıyoruz Çözum Bulan varsa Payalaşablir mi?
> > > 
> > > 
> > > InvoiceManager.php içindeki createDraftBasicInvoice işlevinde
> > > ```
> > > if ($body["data"] != "Faturanız başarıyla oluşturulmuştur. Düzenlenen Belgeler menüsünden faturanıza ulaşabilirsiniz.") {
> > >             throw new ApiException(json_encode($body['data']), 0, null, $body);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Düzeltmelerini düzeltme hatanın nedenini ekranı basar. Muhtemelen sizde de Mükellef güncellemesi hatası verecektir.
> > 
> > 
> > Bende direkt kullanıcı bilgileri güncellenmedi diyor normal e-arşiv e girip güncelleyip oraya kesince sıkıntı yok ama tekrar kütüphaneden girmece kesmiyor ve aynı yanlışlıkla veriyor hata veriyor sonra tekrar e-arşiv portaldende kesmeyip tekrar güncelleme yaparak kesiyor portalı üzerinden
> 
> Hocam bu kısmı anlamadım. e-Arşive topluyorsunuz güncelliyorsunuz ordan kesebiliyorsunuz. Sonra tekrar kütüphaneden birbirine geçirmeye çalışıyorsunuz hata veriyorsunuz. --> Buraya kadar tamam. Sonra tekrar E-Arşiv portalından kesmek için 2. varsayılanı güncellemeniz mi gerekli?
> 
> Böyleyse kütüphena e-arşivdeki bilgileri sıfırlanıyor o zaman?

Bir Deva GIB Portalda Bilglierli Yazında Daha Bilgiler Silinmıyor ama Kütüphanede aynı hata dönüyor Bende Bilgiler Silinmedi Daha

**Comment by erenn44** [comment]
> a tekrar E-Arşiv portalden kesmek için 2. defa güncelleme yapmanız mı gerekli

aynen hocam kütüphaneden deneyip tekrar e-arşiv e girince orada da hata veriyor sonra girip bilgilere baktığımda herşey yerinde duruyor ama güncelle butonuna basınca e-arşiv portalden kesiyor yoksa orada da hataya düşüyor

**Comment by muglali20** [comment]
GİB Nasıl Bir Güncelleme Yaptı ki onuda Bilemıyoruz ki kütüphanede Güncelleme Yapalım Güncellemeyi Nasıl Öğrenebiliriz acaba

**Comment by blackhawktr** [comment]
> GİB Nasıl Bir Güncelleme Yaptı ki onuda Bilemıyoruz ki kütüphanede Güncelleme Yapalım Güncellemeyi Nasıl Öğrenebiliriz acaba

İşte onu bir öğrenebilsek.. Bunun bir API dökümantasyonu falan da yok. Üşenmedim kütüphaneyi baştan aşağı da okudum. Dispatch URL Internal Server Error veriyor bununla alakalı mı dicem ama LTD lerde yani Ad soyad güncellemesi olmayanlarda kütüphane hala çalışıyor.

**Comment by erenn44** [comment]
> > GİB Nasıl Bir Güncelleme Yaptı ki onuda Bilemıyoruz ki kütüphanede Güncelleme Yapalım Güncellemeyi Nasıl Öğrenebiliriz acaba
> 
> İşte onu bir öğrenebilsek.. Bunun bir API dökümantasyonu falan da yok. Üşenmedim kütüphaneyi baştan aşağı da okudum. Dispatch URL Internal Server Error veriyor bununla alakalı mı dicem ama LTD lerde yani Ad soyad güncellemesi olmayanlarda kütüphane hala çalışıyor.

Hımm bak LTD'lerde denemedim ben birde onlardan deneyeyim

**Comment by muglali20** [comment]
> a keserken e-arşiv de tüm ağı izledim hiçbir fark göremedim nasıl olduysa genel anlamda başka kişilerde e-arşiv portalde bu hata çıkmı

Ne Yaptınız Hocam :)

**Comment by erenn44** [comment]
> Aha @erenn44 senin söylediğinden yola çıkarak denedim sorunsuz çalıştı.

ne yaptınız hocam peki bizede söylermisiniz

**Comment by erenn44** [comment]
ben sabahtan bu yana denemediğim birşey kalmadı

**Comment by blackhawktr** [comment]
Hocam hemen birazdan söylicem. Tekrar test ediyim de sizi de boşuna yormuş olmayayım

**Comment by blackhawktr** [comment]
Hocam şöyle bi deneyin.
Oluşturacağınız faturayı Post ettiğiniz sayfadaki

```
$client = new InvoiceManager();
$client->setUsername($this->user)->setPassword($this->pass);
$client->connect();
```

satırlarının altına

```
$userInformations = $userInformations->setAd("ŞAHIS FİRMASI AD")->setSoyad('ŞAHIS FİRMASI SOYAD');
$client->setUserInformations($userInformations); 
$client->sendUserInformationsData(); 
```

satırlarını ekleyin.

Sonucu bana da bildirirseniz sevinirim.

**Comment by muglali20** [comment]
> Hocam şöyle bi deneyin. Oluşturacağınız faturayı Post ettiğiniz sayfadaki
> 
> ```
> $client = new InvoiceManager();
> $client->setUsername($this->user)->setPassword($this->pass);
> $client->connect();
> ```
> 
> satırlarının altına
> 
> ```
> $userInformations = $userInformations->setAd("ŞAHIS FİRMASI AD")->setSoyad('ŞAHIS FİRMASI SOYAD');
> $client->setUserInformations($userInformations); 
> $client->sendUserInformationsData(); 
> ```
> 
> satırlarını ekleyin.
> 
> Sonucu bana da bildirirseniz sevinirim.

Fatal error: Uncaught Error: Call to a member function setAd() on null in /home/**/public_html/gibarsiv.php:135 Stack trace: #0 {main} thrown in

hatasını veriyor Hocam

**Comment by blackhawktr** [comment]
InvoiceManager.php dosyanızda
`use furkankadioglu\eFatura\Models\UserInformations;`
yok mu?

Kütüphanenin orjinalinde UserInformations fonksiyonları mevcut.

**Comment by blackhawktr** [comment]
Hocam özür dilerim.

```
$userInformations = $client->getUserInformationsData();
$userInformations = $userInformations->setAd("ŞAHIS FİRMASI AD")->setSoyad('ŞAHIS FİRMASI SOYAD');
$client->setUserInformations($userInformations); 
$client->sendUserInformationsData(); 
```

Buraya kopyalarken ilk satırı seçmeyi unutmuşum.

**Comment by muglali20** [comment]
Şimdi Ekledim
Fatal error: Uncaught Error: Call to a member function setAd() on null in /home/*/public_html/gibarsiv.php:137 Stack trace: #0 {main} thrown in

Bu Şekilde Oluyor

**Comment by muglali20** [comment]
Çok Teşekkürler Oldu Hocam

**Comment by blackhawktr** [comment]
Rica ederim hocam ne demek hayır duanızı da aldıysam benden kârlısı yok :)

**Comment by erenn44** [comment]
Bende şimdi deneyeceğim hemen

**Comment by erenn44** [comment]
> Bende şimdi deneyeceğim hemen

Hata bendede bu çözüm ile sonuçlanmıştır.
