### ISSUE TITLE
Sunucu tarafli hata olustu

### ISSUE THREAD

**Issue by tkalfaoglu** [furkankadioglu/efatura#109]
Merhabalar.. deneme programinin neredeyse aynisini yazdim, production bilgilerini girdim, ama:

```
PHP Fatal error:  Uncaught furkankadioglu\eFatura\Exceptions\ApiException: Sunucu taraflı bir hata oluştu! in /var/www/vhosts/kalfaoglu.net/httpdocs/deneme/vendor/furkankadioglu/efatura/src/InvoiceManager.php:341
Stack trace:
#0 /var/www/vhosts/kalfaoglu.net/httpdocs/deneme/vendor/furkankadioglu/efatura/src/InvoiceManager.php(308): furkankadioglu\eFatura\InvoiceManager->checkError(Array)
#1 /var/www/vhosts/kalfaoglu.net/httpdocs/deneme/vendor/furkankadioglu/efatura/src/InvoiceManager.php(242): furkankadioglu\eFatura\InvoiceManager->getTokenFromApi()
#2 /var/www/vhosts/kalfaoglu.net/httpdocs/deneme/test.php(20): furkankadioglu\eFatura\InvoiceManager->connect()
#3 {main}
  thrown in /var/www/vhosts/kalfaoglu.net/httpdocs/deneme/vendor/furkankadioglu/efatura/src/InvoiceManager.php on line 341
```

Neyi yanlis yapiyorum acaba?  PHP 7.2.24...
Cok tesekkurler!! 
-t

**Comment by tkalfaoglu** [comment]
Simdi fark ettim ki   setDebugMode(true) yaparsam hata vermiyor.. ama false yaparsam yukaridaki hatayi aliyorum..

**Comment by gvngzl** [comment]
Merhaba aynı sorunu bizde yaşıyoruz. zaten setDebugMode false olursa işlem yapmıyor hatayı da göstermiyor.  o yüzden hata almıyorsunuz ama bu sorunu nasıl çözebiliriz ?

Kolay Gelsin.

**Comment by russh3l** [comment]
> Author
problemi çözdünüz mü? Mart ayında çalışan sistem şu anda çalışmıyor ne değişiklik oldu bulamıyorum ..

**Comment by gvngzl** [comment]
Bende çalışıyor sadece dediğim gibi getDownloadURL kullanıyorsanız o çalışmıyor.

**Comment by tkalfaoglu** [comment]
Ok deneme programindayim..

// Production environment
$client->setUsername("4565461217")->setPassword("565451");
// Test Environment
$client->setDebugMode(false)->setTestCredentials();
echo "<h1>Credentials</h1>";
echo "<pre>";
print_r($client->getCredentials());
echo "</pre>";

burada patlıyor:
php exam.php 
<h1>Credentials</h1><pre>Array
(
    [0] => 33333301
    [1] => 1
)
</pre>PHP Fatal error:  Uncaught furkankadioglu\eFatura\Exceptions\ApiException: Sunucu taraflı bir hata oluştu! in InvoiceManager.php:341

**Comment by tkalfaoglu** [comment]
AHA!   Buldum sebebini..
$client->setDebugMode(false)->setTestCredentials(); 
Bu satır OLMAYACAK.. Bunu çıkarınca çalışıyor. ben hiç test modunu kullanmayıp faturaları silerim elle dedim.. false a ayarladım.. ama false olunca gerisi çalışmıyor.
