### ISSUE TITLE
Detay

### ISSUE THREAD

**Issue by altunsoft-yazilim** [furkankadioglu/efatura#115]
Merhaba, kurulumun detayından bahseder misiniz?

**Comment by furkankadioglu** [comment]
efatura bir php paketidir, php'de bulunan en yaygın paket yöneticisi olan composer ile indirebilirsiniz. Ya da kendiniz kaynak kodlarını indirip projenize taşıyabilirsiniz ancak bu çok uğraştırıcı olur. Kuracağınız bir şey bulunmuyor, örneklemek gerekirse bu bir yemek değil yemek kitabı ve yemek malzemeleri olarak kabul edebilirsiniz. Siz bu malzemelerle istediğiniz sisteme, istediğiniz şekilde entegre edebilir ya da kendiniz bu paketin üzerine bir proje geliştirebilirsiniz.

PHP'de paket yönetimi, composer ve autoload gibi terimleri incelemenizi ve araştırmanız bu konuda daha hızlı hareket etmenizi sağlar, kolaylıklar dilerim.
