### ISSUE TITLE
selamlar

### ISSUE THREAD

**Issue by yemrekula0748** [furkankadioglu/efatura#116]
merhaba furkan bey,
kendimiz için ufak çaplı earşiv fatura kesme işlemleri yapabileceğim birşey yapmak istiyorum. php öğrenmeye yeni yeni başladım. acaba müsait bir zamanınızda bir adet fatura kesen bir php dosyası atabilirmisiniz. selam ve saygılarımla...

**Comment by alihan0** [comment]
> merhaba furkan bey, kendimiz için ufak çaplı earşiv fatura kesme işlemleri yapabileceğim birşey yapmak istiyorum. php öğrenmeye yeni yeni başladım. acaba müsait bir zamanınızda bir adet fatura kesen bir php dosyası atabilirmisiniz. selam ve saygılarımla...

merhabalar, 

yazarın paylaşmış olduğu bu kütüphane hali hazırda fatura kesme işine yarıyor. Talimatları takip ederek doğru bir şekilde kurulum yaptığınız zaman fatura kesmeye başlayabileceksiniz, ekstra özel bir işleme gerek yok.

**Comment by furkankadioglu** [comment]
Yanıtın için teşekkür @alihan0. Github projesinin girişinde bir çok örnek kullanım mevcut. Aynı zamanda tests dizinine de bakabilirsiniz orada da bir kaç örneği ve testi bulunuyor.
