### ISSUE TITLE
Oluşturulan Faturayı PDF ye Dönüştürme

### ISSUE THREAD

**Issue by muglali20** [furkankadioglu/efatura#117]
Merhaba;
Fatura Oluşturduğumuzda Dönen HTML Formattakı Faturayı Aynı Şekilde PDF e Nasıl Dönüştürebilirim Birkaç kütüphanede denedim ama Faturadaki QR kod Kayboluyor QR kod ve karakterler aynı şekilde olarak HTML yi direk PDF ye PHP Dilinde Çevirmem konusunda Destek olabilir Mısınız?

**Comment by furkankadioglu** [comment]
Bu konu hakkında giriş bölümünde bilgi bulabilirsiniz, kullanım örneği mevcut.
`$client->getInvoicePDF();`

HTML verisinde QR kod düzgünse PDF'de de düzgün çalışır diye tahmin ediyorum, tabi incelemek gerekir. Ancak şu ana kadar paketin içinde bulunan PDF generatordan bir sorun yaşamadık.
