### ISSUE TITLE
'furkankadioglu\eFatura\Interaktif' not found

### ISSUE THREAD

**Issue by turkbelge** [furkankadioglu/efatura#119]
Geçen yıl oluşturduğum projemi kontrol ettiğimde böyle bir hata alıyorum. Bunun yerine kullanabilceğim bir sınıf var mı?

**Comment by furkankadioglu** [comment]
Interaktif diye bir sınıfımız yok muhtemelen projenizdeki başka bir yapıyla karıştırıyorsunuz.
