### ISSUE TITLE
E-Fatura ve E-Arşiv farkı

### ISSUE THREAD

**Issue by pseudonymousUser** [furkankadioglu/efatura#121]
Muhasabe konusuna biraz uzağım, araştırırken şöyle bir ibare gördüm;

> E-Fatura; faturalarınızı elektronik ortamda düzenleyebilme, iletebilme ve saklayabilme imkanı sunan sistemdir. E-Arşiv Fatura ise, e Fatura sistemine kayıtlı olmayan kişi ve kuruluşlara düzenlenen e-Faturalardır. E-Arşiv sistemi aracılığıyla düzenlenir, gönderilir ve saklanır. Yani bu iki çözüm arasındaki temel fark kullanıcının e-Fatura kullanıcısı olup olmadığıdır.

Yani e-fatura ve e-arsiv farklı şeyler, dökümantasyonda bunun ayrımıyla ilgili herhangi bir bilgi göremedim. Böyle bir ayrım yapmaya gerek mi yok? Yoksa farklı bir durum mu var? Konuyla ilgili bilgisi olan biri konuya açıklık getirirse sevinirim.

**Comment by atak011** [comment]
E-Arşiv fatura herkese kesilebilir ama E-Fatura sadece efatura mükelleflerine kesilebilir yani karşı taraf e fatura mükellefi ise mecburen e fatura kesmelisiniz e fatura müşterisine e arşiv kesilemez

**Comment by pseudonymousUser** [comment]
yani bu uygulamayı kullanarak sadece e-arsiv kesebiliyoruz, e-fatura kesemiyoruz. böyle anladım, doğru mudur acaba?

**Comment by muratcesmecioglu** [comment]
> yani bu uygulamayı kullanarak sadece e-arsiv kesebiliyoruz, e-fatura kesemiyoruz. böyle anladım, doğru mudur acaba?

evet, doğrudur.

**Comment by atak011** [comment]
> yani bu uygulamayı kullanarak sadece e-arsiv kesebiliyoruz, e-fatura kesemiyoruz. böyle anladım, doğru mudur acaba?

doğrudur o yüzden özel entegratörlerle çalışılması lazım
