### ISSUE TITLE
Kurulumda yardıma ihtiyacım var 

### ISSUE THREAD

**Issue by burhankisioglu** [furkankadioglu/efatura#123]
Merhabalar ,

Natroda paylaşımlı hosting kullanıyorum ve sunucuda composer kurulu durumda . Fakat  " composer require furkankadioglu/efatura
" kurulumu nasıl yapacağım bilmiyorum yardım eder misiniz?

**Comment by atak011** [comment]
natro shared hostinglerde composer require yapamazsınız o sebeple ya terminal erişimi olan bi sunucu seçiceksiniz veya VDS/VPS

**Comment by furkankadioglu** [comment]
Bu işlemi localinizde yapmalısınız. Projeyle alakalı bir sorun olmadığından kapatıyorum.

**Comment by hasirciogli** [comment]
Hocam PCnize composer kuracaksınız ardından bağımlılıkları kurup takibinde sucunucuya prod olarak yukleyeceksiniz projenizi. Ve yüklerken vendor klasörünü de alacaksınız. Tavsiyem build alıp zipleyin sonra FTP ile yükleyin ardından cpanel veya plesk FM den zipi çıkartın.
