### ISSUE TITLE
E FATURA 

### ISSUE THREAD

**Issue by mehmetbtr73** [furkankadioglu/efatura#128]
Merhabalar ben bir muhhasebe programı geliştiriyorum ve bu programda fatura kesilmesinide istiyorum bu api bunun için uygunmudur yani özel entegratör kullanmadan fatura kesebiliyormuyuz bununla veya herhangi bir ücret varmmı kullanırken

**Comment by furkankadioglu** [comment]
Evet fatura kesebilirsiniz, ücretsizdir. Açıklamayı okuyabilirsiniz.
