### ISSUE TITLE
İmzalama

### ISSUE THREAD

**Issue by muzafferuyar** [furkankadioglu/efatura#13]
Öncelikle bu ince işçilik için teşekkür ederim. 

Ancak aşağıdaki imzalama aşamasında "Bu işlem için yetkiniz yok" diye hata dönüyor.

`$client->signDraftInvoice();`

İmzalamadan önce sms onayı yapmak mı gerekiyor? Eğer öyleyse telefona gelen sms kodunu ekrana girmek gerekeceği için fatura oluşturma ve imzalama aşamalarının tamamı sunucu tarafında otomatik yapılamayacak anlamına mı geliyor?

**Comment by furkankadioglu** [comment]
Merhaba ben teşekkür ederim @muzafferuyar,

Test hesaplarıyla giriş yapıyorsan eğer, test hesapları SMS gönderemediği için öyle bir uyarı alıyorsundur. Bildiğim kadarıyla gerçek kişi/şirket hesaplarında böyle bir problem yok. 

Faturayı kestikten sonra faturayı imzalaman gerekiyor, ancak fatura ile imza arasında bir bağlantı kurulmamış devletin teknik altyapısında (biz de kodlarken çok şaşırmıştık), bu nedenle faturayı belirtmiyoruz.

Lütfen giriş yaptığın hesabın gerçek bir hesap mı yoksa test hesabımı olduğunu söyleyebilir misin?

Teşekkürler.

**Comment by muzafferuyar** [comment]
Gerçek bir şirket hesabıyla yapıyorum. Ancak taslak olarak faturayı oluşturduktan hemen sonra direkt imzalama fonksiyonunu çalıştırıyorum. 

`
$client->createDraftBasicInvoice(); //bu aşamaya kadar sorunsuz geliyor
$client->signDraftInvoice(); //bunu eklediğimde faturayı onaylamıyor ve yetki hatası dönüyor`

Yani sms onayı yapmıyorum ve aldığım hata "Bu işlem için yetkiniz yok". Sormak istediğim de buydu sms onayını bu aşamada mı yapmamız gerekiyor?

Eğer öyleyse, müşterilerimiz sitemizden satın alım yaptıklarında otomatik kesilen her faturaya tek tek sms onayı yapacaksak bunu nasıl otomasyona bağlayacağız. İnsan müdahelesi olmadan kesilen faturayı resmileştiremiyor muyuz? Aklıma gelen sms'leri sunucuda okuyup onay işlemini de sunucuda yaptırmak geldi ama aynı anda gelen sms şifreleri nedeniyle bu da sekteye uğrayabilir. Resmileştirme aşamasında kafam çok karıştı açıkçası.

**Comment by ahmeti** [comment]
Merhaba @muzafferuyar,

Bu paket; SMS ile doğrulamadan, direkt olarak faturayı imzalıyordu. Fakat bugün gerçek şirket bilgileri ile denemedim.

Açıkçası GİB'in yeni bir güncelleme yapıp, yapmadığını da merak ediyorum. 

Konu ile ilgili birkaç soru sormak istiyorum.

1. Aynı kullanıcı bilgileri ile daha önce **$client->signDraftInvoice()** çalışıyor muydu? 
2. Daha önce çalışıyorsa, bugün mü bu hatayı almaya başladın?
3. Paketi bugün ilk kez mi kullanmaya başladın?

İyi çalışmalar.

**Comment by furkankadioglu** [comment]
> Eğer öyleyse, müşterilerimiz sitemizden satın alım yaptıklarında otomatik kesilen her faturaya tek tek sms onayı yapacaksak bunu nasıl otomasyona bağlayacağız. İnsan müdahelesi olmadan kesilen faturayı resmileştiremiyor muyuz? Aklıma gelen sms'leri sunucuda okuyup onay işlemini de sunucuda yaptırmak geldi ama aynı anda gelen sms şifreleri nedeniyle bu da sekteye uğrayabilir. Resmileştirme aşamasında kafam çok karıştı açıkçası

Yarın bir fatura keseceğim, o süreçte tekrardan requestleri inceleyip bir güncelleme olup olmadığına bakarım. @ahmeti'nin sorularını yanıtlaman çok yardımcı olabilir bize.

Soruna yanıt vereyim: Açıkçası bu doğrulama konusunda çok arada kalmışlar. Faturaları onaylatmadan da onaylı PDF'i alabiliyoruz. Bu example klasöründe bulunan örnekte de mevcut. Ancak sonradan toplu olarak imzalanabilir, bu konuda bir özellik eklemişlerse kütüphaneye dahil edeceğim.

**Comment by muzafferuyar** [comment]
> 
> 
> Merhaba @muzafferuyar,
> 
> Bu paket; SMS ile doğrulamadan, direkt olarak faturayı imzalıyordu. Fakat bugün gerçek şirket bilgileri ile denemedim.
> 
> Açıkçası GİB'in yeni bir güncelleme yapıp, yapmadığını da merak ediyorum.
> 
> Konu ile ilgili birkaç soru sormak istiyorum.
> 
>     1. Aynı kullanıcı bilgileri ile daha önce **$client->signDraftInvoice()** çalışıyor muydu?
> 
>     2. Daha önce çalışıyorsa, bugün mü bu hatayı almaya başladın?
> 
>     3. Paketi bugün ilk kez mi kullanmaya başladın?
> 
> 
> İyi çalışmalar.

Merhaba,

Bu soruyu yazdığımda ilk kez denedim ve hata aldım. Paketi de aynı şekilde ilk defa kullandım, daha önce aynı kullanıcıyla bu paket dahil hiçbir paket ile gib üzerinden elle fatura kesmek ve yasallaştırmak dışında işlem yapılmadı. Diğer javascript ve php paketlerinin de kaynak kodlarını inceledim ancak birebir aynı yöntemle imzalama yaptıklarını gördüm. 

@furkankadioglu'nun da bahsettiği gibi imzalamadan pdf çıktısı alınabiliyor, üzerinde de normalde gibden alınan imzasız faturalardaki gibi "imzasız" ibaresi bulunmuyor. Ancak bunu müşteriye bu aşamada göndermenin yasal tarafı nedir bilmiyorum. Müşteri biz imzalamadan önce işleme koyarsa sorun yaratabilir. Bizim de aklımıza sonradan toplu olarak manuel imzalama seçeneği geldi. Şu an için öyle kullanıyoruz hatta. Tabi otomatik olsa harika olurdu, kesildiği gibi müşteriye mail olarak gönderebilirdik.

Tekrardan bu temiz işçilik için teşekkür ediyorum.

**Comment by furkankadioglu** [comment]
Araştırmam biraz uzun sürdü lütfen kusura bakma @muzafferuyar

Geri bildirim verdiğin için biz teşekkür ederiz, ancak malesef iyi haberlerim yok. Şu an kullanılan fonksiyonumuz dışında herhangi bir alternatif yok. POS'lardaki gün sonu gibi bir işlem ile toplu imzalama en mantıklısı olur. Malesef başka bir seçenek gözükmüyor. 

Mevcut imzalama fonksiyonunu test edemedim, hattı dinlediğim için. Ancak o tarafta bir eksik veya hata varsa lütfen yaşadığın sorunu da bize bildir ki yardımcı olabilelim. Başka bir imzalama yöntemi gelene kadar malesef en iyisi (ve tek olan) bu.
