### ISSUE TITLE
genel Sistem Hatası:java.lang.NullPointerException

### ISSUE THREAD

**Issue by instacod2** [furkankadioglu/efatura#14]
Taslaklara kaydedilmiş faturayı sms doğrulaması için kod gönderdikten sonra gelen kodu giriyorum ancak,

genel Sistem Hatası:java.lang.NullPointerException

şeklinde bir hata dönüyor.

**Comment by furkankadioglu** [comment]
Merhaba @instacod2 

SMS Doğrulamasının yapısını sanırım değiştirdiler, bu nedenle böyle bir hata görünüyor. Parametrelerdeki değişiklikleri tespit edip projeyi güncelleyeceğim.

Sorunu bildirdiğin için teşekkürler.

**Comment by crazyshark2** [comment]
Çok seviniriz bizde aynı hatayı alıyoruz ve bulamadık. Şimdiden çok teşekkür ederiz. Ellerinize emeğinize sağlık.

**Comment by furkankadioglu** [comment]
Bilgi vermek istedim,

Öncelikle uzun beklettiğim için üzgünüm, e-arşivin test sisteminde her şey var ancak sms ile doğrulama yok. Onu ordan test edemiyoruz, dolayısıyla gerçekten fatura kesip onaylatmam gerekiyor. Bu nedenle ay başına kadar beklemek zorunda kaldım. Şu an tüm trafik datasını aldım, bir kaç gün içinde (muhtemelen bu akşam) gerekli güncellemeyi yapıcam. 👍 

@crazyshark2 @instacod2

**Comment by crazyshark2** [comment]
Çok gizli değil veya zor değilse değişen kodun nasıl bulunduğunu paylaşabilirsen ileriki zamanda earsivportal da bir değişiklik olduğunda buradan yardımcı olmaya çalışabiliriz merak eden veya sorun yaşayanlara. Gerçekten güzel bir çalışma tekrardan eline emeğine sağlık.

**Comment by furkankadioglu** [comment]
Yok tabi ki değil, Chrome'dan debug tools a girip Network tabında giden istekleri ve gelen yanıtları görebilirsiniz. Ben teşekkür ederim haber verdiğiniz için :)

**Comment by crazyshark2** [comment]
Bende oradan bakıyorum ama yakalayamadım ufak bi yalnışlık yapıyorum sanırım ama nerede onu anlayamadım onaylanınca yeni fatura oluşturmam gerekli çok fazla deneyemiyorum :)
Sanırım bi fırın ekmek daha yemem lazım. Bekliyorum çok teşekkür ederiz şimdiden.

**Comment by crazyshark2** [comment]
Merhabalar Sağlıklı günler dilerim Düzeltmeye bakabilme şansınız oldumu?

**Comment by furkankadioglu** [comment]
Merhaba, bilgilendirmek istedim, SMS doğrulama sisteminde köklü değişiklikler yapılmış. Değişim biraz sürecek ancak diğer tüm kısımları şu an aktif olarak kullanabilirsiniz. En kısa zamanda yapmaya çalışacağım.


RG_SMSONAY komutuyla giden fonksiyonu değiştirmişler (bu smsin onayı için başlatılan fonksiyon) ancak SMS GONDERME fonksiyonunda bulunmayan bir değişken ile yapıyorlar bu işlemi. Bağlantıyı anlamam için biraz vakit lazım. 😞

**Comment by crazyshark2** [comment]
Hergün bakıyorum desem yeridir. Bi eksik daha gitmiş olucak listeden :) Şimdiden çok teşekkür ederim.

**Comment by furkankadioglu** [comment]
@crazyshark2  @instacod2 Merhabalar, biraz geç oldu yazmak için ancak çok önce bir pull request ile bu sorunu çözdük sanıyorum. Deneme imkanınız olursa haber verebilir misiniz?

**Comment by furkankadioglu** [comment]
Lütfen çalışmaması durumunda tekrar haberleşelim.

**Comment by crazyshark2** [comment]
Merhabalar kusura bakmayın dönemedim. Bir arkadaşımız yazılımını gerçekleştiriyor fakat şuan yurtdışında tatil olduğundan biraz bekletiyor bizi dönücem yapıldıktan sonra. Emeğinize sağlık şimdiden

**Comment by crazyshark2** [comment]
Ellerinize emeğinize sağlık çok teşekkür ederim. İmzalamayı başarabildik sonunda.
