### ISSUE TITLE
SMS Doğrulaması Hata Kontrolü

### ISSUE THREAD

**Issue by brkygncn** [furkankadioglu/efatura#18]
verifySMSCode fonskiyonunda dönen verinin checkError ile hata kontrolüne ek olarak $body["data"]["sonuc"] alanının da kontrolü gerekiyor. 

Şu anki sistemde SMS şifresi hatalı girilse bile array üzerinde bir error kümesi dönmediği için işlem başarılı kabul edilip bağlı diğer işlemler devam ediyor. Şu sıralar pek vaktim olmadığı için pull request gönderemedim, kusura bakmayın.
 
$body ile gelen dönüşler hatalı ve başarılı sonuçlar için aşağıdaki şekilde:

# Başarısız Dönüş
Array ( [data] => Array ( [msg] => SMS şifrenizi yanlış girdiniz [sonuc] => 0 ) [metadata] => Array ( [optime] => 20210116133633+0300 ) )

# Başarısız Dönüş
Array ( [data] => Array ( [msg] => SMS şifreniz doğrulandı, işlem başarılı. [sonuc] => 1 ) [metadata] => Array ( [optime] => 20210116133544+0300 ) )

**Comment by furkankadioglu** [comment]
Merhaba, gerekli güncellemeyi yapacağım. Belirttiğiniz için çok teşekkürler. 

Katkı sağlayanlarda çıkmak isterseniz, pull request atarsanız da kabul ederim. :)

**Comment by furkankadioglu** [comment]
Eklendi. Siz de test ederseniz çok sevinirim.
