### ISSUE TITLE
Sunucuda fatura sayfasından çıkış

### ISSUE THREAD

**Issue by PremiumTurk** [furkankadioglu/efatura#2]
Hocam sunucu tarafında bir logout sınıfı var mı acaba ? Sunucudan 1 defa giriş yapınca portalda giriş görülüyor başka yerden giriş sağlanamıyor. İşlem bitişinde logout versek başka yerlerden de bağlatılar açılsa ?

**Comment by furkankadioglu** [comment]
Merhaba @PremiumTurk 

Öncelikle geribildirimin için teşekkür ederim. Logout tarafını inceledim, gayet yapılabilir gözüküyor. Maksimum 2 gün içerisinde (tahminen bugün) gerekli düzenlemeyi yapmış olacağım.

**Comment by furkankadioglu** [comment]
Merhaba, 

1.6.1 güncellemesiyle logOutFromAPI fonksiyonu eklendi. Token ile sunucu tarafından çıkışı sağlayıp InvoiceManager'dan token değişkenini de siliyor.

**Comment by PremiumTurk** [comment]
> Merhaba,
> 
> 1.6.1 güncellemesiyle logOutFromAPI fonksiyonu eklendi. Token ile sunucu tarafından çıkışı sağlayıp InvoiceManager'dan token değişkenini de siliyor.

Teşekkürler

**Comment by PremiumTurk** [comment]
> Merhaba,
> 
> 1.6.1 güncellemesiyle logOutFromAPI fonksiyonu eklendi. Token ile sunucu tarafından çıkışı sağlayıp InvoiceManager'dan token değişkenini de siliyor.

Çıkış fonksiyonu çalışıyor fakat sistem hala giriş yapılı şekilde gösteriyor. [Hata Görseli](https://bahadirsuzen.com.tr/uploads/screenshot_1.png)
