### ISSUE TITLE
fatura okuma

### ISSUE THREAD

**Issue by tazefikirler** [furkankadioglu/efatura#22]
merhaba gib kullanıcı adı şifre ile bu yapı  üzerinden adıma kesilen  faturaların görünümlerini görmek indirmek mümkünmü?

söyle söyleyeyim interaktif vergi dairesinde adımıza kesilen 1 haftalık tarih aralığı ile  faturalar görüntüleniyor  ancak sadece tutar kdv vs. içerik vb kalemler görünmüyor bunu görüntüleme mümkünmü? yada seçilen faturanın içerigine nasıl erişilir. bir örnek varmıdır.? teşekkürler

**Comment by ahmeti** [comment]
Merhaba @tazefikirler,

Maalesef e-arşiv portaldan sadece fatura gönderebilirsiniz. Size kesilen faturaların başlığını ya da içeriğini görüntüleyemezsiniz. 

Sizin de belirttiğiniz gibi size gönderilen fatura başlıklarını interaktif vergi dairesinden görüntüleyebilirsiniz.

Fatura İçeriğini, size e-posta ile gönderilen XML dosyasından okuyabilirsiniz. E-fatura mükellefi değilseniz bunu okuyabileceğiniz başka bir yöntem maalesef bulunmamaktadır.

İyi çalışmalar.

**Comment by furkankadioglu** [comment]
@ahmeti nin yanıtına katılmakla birlikte, e-vergi dairesinde böyle bir bölüm var, oradan bu işlemi yapabilirsiniz ancak bu proje maalesef onu kapsamıyor.
