### ISSUE TITLE
Yeni fatura oluşturmada Teknik bir hata oluştu. uyarısı

### ISSUE THREAD

**Issue by ibrcan** [furkankadioglu/efatura#27]
Yeni bir fatura taslağı oluşturmaya çalıştığım zaman sunucudan **teknik bir hata oluştu** mesajı alıyordum. 
**$fatura_detaylari["malHizmetTable"]** dizide bulunan **iskontoArttm** anahtarı olmaz ise iskontolu bir  fatura oluştururken sıkıntı oluyormu bilmiyorum ancak iskontosuz fatura taslağı oluştururken bu değeri kaldırdım ve **iskontoNedeni** isminde başka bir boş key oluşturarak problemi çözdüm.

**Comment by muratcesmecioglu** [comment]
Bugün yaptığım testlerde iskontoArttm parametresi olmadan da fatura oluşturulabiliyor.
iskontoNedeni parametresinde gönderilen değer, faturadaki iskonto sütununda ilgili ürünün hizasında "İskonto - [iskontoNedeni] " şeklinde çıkıyor.

**Comment by furkankadioglu** [comment]
@ibrcan composer update yaptıktan sonra hata almaya devam ediyor musunuz?

**Comment by furkankadioglu** [comment]
Uzun süre yanıt alınamadığı için kapatıyorum.
