### ISSUE TITLE
Sunucuyu test aşamasından çıkartma ve aktifleştirme

### ISSUE THREAD

**Issue by PremiumTurk** [furkankadioglu/efatura#3]
Test sunucusundan çıkıp normal sunucuya geçmeyi yapamayanlar için `$client->setDebugMode(true)->setTestCredentials();` kodu test aşamasını sağlarken bu satırı yorum satırına çevirip yeni satırda `$client->setDebugMode(false);` ekleyerek test sunucusundan çıkıp ana işleme geçebilirsiniz.

**Comment by PremiumTurk** [comment]
Bende geliştirme yapıyorum şimdi yanlış olursa uyarın lütfen.

**Comment by furkankadioglu** [comment]
setTestCredentials fonksiyonu test kullanıcı bilgilerini sunucudan almak içindir.  Canlı sunucuya geçmek için setCredentials(kullanici_adi, sifre) fonksiyonunu kullanip, debugMode'u kapatmanız gerekmektedir. Ardından da connect fonksiyonunu kullanabilirsiniz.
