### ISSUE TITLE
Merhabalar , E-arsiv portal Güncellendi ve çalışmıyor (Acil yardıma ihtiyacım var !)

### ISSUE THREAD

**Issue by rakstk** [furkankadioglu/efatura#31]
Merhabalar, 2 gün önce çalışan yazılım artık çalışmıyor, earsiv portala girince değiştiğini görüyorum, değişiklik sebebiyle kodlar yerlerine oturmuyor, hatayı çözmek için çok fazla gezindim ancak bir yola varamadım, lütfen yardımcı olur musunuz çok acil ? :/

**#Sorun Çözüldü - Pdf çıktısını , html olarak düzelttim anlamsızca sorunsuz çalıştı :) Sanırım mpdf te sorun oluştu.**

**Comment by rakstk** [comment]
if ($this->invoice == null) {
            throw new NullDataException("Invoice variable not exist");
        }
Bu hatayı döndürüyor

**Comment by muratcesmecioglu** [comment]
Bugün gelen güncelleme sebebiyle fatura oluşturma ve iptal etme fonksiyonlarında sorun çıkmıştı ancak hızlıca düzeltildi.

**Comment by kbasali** [comment]
Bizde aynı sorun var, 2 gün öncesine kadar normal çalışıyordu ama şu anda faturaları e-arşiv e gönderemiyoruz :(

**Comment by furkankadioglu** [comment]
composer update yaptıktan sonra tekrar dener misiniz? Güncel versiyonda problem devam ediyor mu? @kbasali

**Comment by kbasali** [comment]
@furkankadioglu Bizde sorun hala devam ediyor. Bizdeki sorun sanırım özel entegratör yüzünden olmuş olabilir. 
Profilindeki adrese email attım. Müsait olduğunda bakabilir misin?

**Comment by crazymesut** [comment]
@furkankadioglu UnitType::ADET kısmında bir hata var sanırım,

**Comment by crazymesut** [comment]
@furkankadioglu sorunu buldum CM3 2 defa tanımlanmış

**Comment by furkankadioglu** [comment]
@crazymesut @kbasali versiyon 1.9.2 yayınlandı, bahsettiğiniz problemleri @muratcesmecioglu çözdü. Umuyorum bir problem kalmamıştır.

Buradan da haberini vereyim, versiyon 2.0.0 da yakında yayınlanacak.

**Comment by rakstk** [comment]
Merhaba, @furkankadioglu @muratcesmecioglu İlginiz için teşekkür ediyorum. Şuanda bir sorunum kalmadı. Başarılarınızın devamını diliyorum. İyi çalışmalar. Yeni versiyonlarda görüşmek dileği ile :)

**Comment by crazyshark2** [comment]
Faturadan dönen istek değişmiş sanırım sürekli fatura oluşturuyor

Birde sms deki hata

RESPONSE: {"error":"1","messages":["Genel Sistem HatasÄ±:java.lang.NullPointerException"],"metadata":{"optime":"20210604153907+0300"}}
