### ISSUE TITLE
update problemi

### ISSUE THREAD

**Issue by crazymesut** [furkankadioglu/efatura#32]
Nedendir bilmiyorum ama sadece bu bağılılıkta bir sorun var, composer update ile güncelleme yapmıyor ve hep eski kodlar kalıyor. Sizce sorun nedir? Başka yol ile update var mıdır?

**Comment by ahmeti** [comment]
Tag release edilmediği için update edecek yeni bir versiyon bulamıyor.

composer remove furkankadioglu/efatura

composer require furkankadioglu/efatura:dev-master

Yukarıdaki işlemleri uyguladığınızda güncel versiyona erişmiş olacaksınız.

**Comment by crazymesut** [comment]
Teşekkürler @ahmeti 
Bu arada megatrhost mı çalışıyorsunuz?

**Comment by furkankadioglu** [comment]
@ahmeti uyardığın için çok teşekkürler, son bir kaç test için versiyon güncellemesi yapmamıştık. Sonra da unutmuşuz, son versiyonu packagiste aktardık şu an direkt paket adıyla güncel versiyona erişebilirsiniz.

dev-master çok güncel ancak bazen testlerden geçemeyebiliyor, kullanırken bazı hatalarla karşılaşmanız mümkün olabilir. 

İyi çalışmalar :)
