### ISSUE TITLE
Hata Uyarısı Alıyorum

### ISSUE THREAD

**Issue by bllbgc** [furkankadioglu/efatura#36]
Merhaba hocam. ben bu apiyi sistemime kurdum. bütün fonksiyonlar aktif çalışıyor. fakat yeni fatura oluşturmak isteyince Teknik bir hata oluştu diye bir hata mesajı dönüyor. fatura değişkenlerini defalarca kontrol ettim. number karakterleri string e çevirdim bu kez string array uyarısı aldım. toplamlarda vs hiçbir sorun yok. aynı faturayı portaldan kesiyorum kayıt yapıyor. ama api ile gönderince Hata veriyor. neden olabilir. nerede hata yapıyoruz sizce.

**Comment by muratcesmecioglu** [comment]
Merhaba. Benim test için kullandığım şöyle bir dosya var. Test ortamında fatura oluşturup ekrana basıyor basitçe. Böyle standart bir fatura kesmeye çalışınca da hata veriyor mu?

Test Dosyam: https://gist.github.com/muratcesmecioglu/a69e7143aafdc05719c3a3f5e409f004

**Comment by kbasali** [comment]
Dün fatura kesebiliyordum bugün yine hata veriyor. 
Yine bir güncelleme filan mı oldu  efatura.gov.tr tarafında?

**Comment by bllbgc** [comment]
hocam valla denemediğim değişken kalmadı. hep hata uyarısı verdi. yüzden fazla deneme yaptım. içlerinden bir tanesini kaydetmiş namussuz :) ama hangi şekilde kabul etti bulamadım. muratcesmecioğlu kardeş senin kodu da inceledim. ama değişkenleri birebir yaptım. ama test modunda denemedim. normal modda yine hata verdi.

**Comment by bllbgc** [comment]
hata alan değişkenler bu şekilde.

    [faturaUuid] => 8709f3c6-4da3-4f39-a05d-8abea27997dc
    [belgeNumarasi] => FTP2021000000001
    [faturaTarihi] => 20/05/2021
    [saat] => 12:13:57
    [paraBirimi] => TRY
    [hangiTip] => 5000/30000
    [dovzTLkur] => 0
    [faturaTipi] => SATIS
    [vknTckn] => 6740045788
    [aliciUnvan] => Serdar İslamoğlu Un Mam. Gıda İnş. San. Tic. Ltd. Şti
    [aliciAdi] => 
    [aliciSoyadi] => 
    [binaAdi] => 
    [binaNo] => 
    [kapiNo] => 
    [kasabaKoy] => 
    [vergiDairesi] => Uludağ
    [ulke] => Türkiye
    [bulvarcaddesokak] => Demirtas Cumhuriyet Mh. Cevre Yolu Cd. No. 129 / 4
    [mahalleSemtIlce] => Osmangazi
    [sehir] => Bursa
    [postaKodu] => 
    [tel] => 
    [fax] => 
    [eposta] => 
    [websitesi] => 
    [iadeTable] => Array
        (
        )

    [ozelMatrahTutari] => 0
    [ozelMatrahOrani] => 0
    [ozelMatrahVergiTutari] => 0
    [vergiCesidi] =>  
    [tip] => İskonto
    [matrah] => 42.37
    [malhizmetToplamTutari] => 42.37
    [toplamIskonto] => 0
    [hesaplanankdv] => 7.63
    [vergilerToplami] => 7.63
    [vergilerDahilToplamTutar] => 50
    [odenecekTutar] => 50
    [not] => Elli Liradır
    [siparisNumarasi] => 
    [siparisTarihi] => 
    [irsaliyeNumarasi] => 
    [irsaliyeTarihi] => 
    [fisNo] => 
    [fisTarihi] => 
    [fisSaati] => 
    [fisTipi] => 
    [zRaporNo] => 
    [okcSeriNo] => 
    [malHizmetTable] => Array
        (
            [0] => Array
                (
                    [malHizmet] => Servis Ücreti
                    [miktar] => 1
                    [birim] => C62
                    [birimFiyat] => 42.37
                    [fiyat] => 42.37
                    [iskontoOrani] => 0
                    [iskontoTutari] => 0
                    [iskontoNedeni] => 
                    [malHizmetTutari] => 42.37
                    [kdvOrani] => 18
                    [vergiOrani] => 0
                    [kdvTutari] => 7.63
                    [vergininKdvTutari] => 0
                )

        )

    [data] => Teknik bir hata oluştu.

**Comment by bllbgc** [comment]
sorunu buldum. herkes açısından faydalı olacağını düşünüyorum. sorun mail adresinin doğru formatta olmaması. yani düzgün bir mail adresi post etmezseniz kayıt sorunlu oluyor. şu anda bütün fonksiyonlarını reel olarak çalıştırdım. fatura kesiminde bir problem kalmadı. ilgilenen arkadaşlara teşekkürler.
