### ISSUE TITLE
Düzeltme Hakkında

### ISSUE THREAD

**Issue by okansoft** [furkankadioglu/efatura#41]
Merhaba,
Fatura kestik ve taslaklarda duruyor , kestiğimiz faturayı düzenleme yapabiliyormuyuz ?

**Comment by crazyshark2** [comment]
Onay tuşuna bastıktan sonra değiştiremiyorsun bildiğim kadarıyla. Eskisini iptal edip yeniden oluşturman lazım.

**Comment by furkankadioglu** [comment]
Oluşturduğunuz bir faturayı düzenlemeniz earşiv tarafından kısıtlandırılmış durumda, bu nedenle böyle bir şey yapılamıyor.
