### ISSUE TITLE
PHPv8

### ISSUE THREAD

**Issue by tgedikli** [furkankadioglu/efatura#45]
@furkankadioglu Bey merhaba, 

Projenin composer ayarlarında php sürümü olarak 8 desteklememesinin bir sebebi var mı? Eğer yok ise bir PR göndereceğim

**Comment by furkankadioglu** [comment]
@tgedikli Hatırladığım hiç bir geçerli sebep yok, gönderirseniz harika olur. Emeğinize sağlık! :)
