### ISSUE TITLE
ApiException print_r response hatası

### ISSUE THREAD

**Issue by ahmeti** [furkankadioglu/efatura#5]
Merhaba Furkan,

Öncelikle bu paketi bizimle paylaştığın için teşekkür ederim.

Aşağıdaki ApiException metodunda print_r fonksiyonuna true parametresi gönderilmediği için exceptionlar yakalansa bile print_r datayı response ediyor. Dolayısıyla exceptionun yakalanmasının bir anlamı kalmıyor.

https://github.com/furkankadioglu/efatura/blob/0aa05aceb85e365886235a161de3536e1fa8fe03/src/InvoiceManager.php#L327

Teşekkür ederim, iyi çalışmalar.

**Comment by furkankadioglu** [comment]
Merhaba @ahmeti 

Kullandığın ve hata bildirdiğin için ben de çok teşekkür ederim. Bir kaç dakika içerisinde düzelmiş olacak.

**Comment by furkankadioglu** [comment]
1.7.2 ile sorun çözülmüş olmalı. 🚀
