### ISSUE TITLE
SMS onay sorunu 

### ISSUE THREAD

**Issue by sercanaydin** [furkankadioglu/efatura#58]
Merhaba,
aşağıdaki method ile sms kodunu ve operasyon numarasını gönderiyorum sonuç true dönmesine rağmen fatura onaylanmıyor. Daha önce bu sorunla karşılaşan oldu mu? 

$client->verifySMSCode($request->code, $invoice->operation_id);

NOT: Kendi özel projemde kullanacağım yasal mevzuatta bir problem oluşturur mu ? Herhangi bir yerden izin almam gerekiyor mu ?

**Comment by muratcesmecioglu** [comment]
Merhaba,

Yakın zamande keseceğim bir faturam yok fakat ilk fatura kesme işlemimde sms kısmını test edeceğim.

Özel bir izin almanıza gerek yok. Yasal mevzuatta bu kütüphane ile fatura oluşturmanız bir problem çıkartmaz ancak README bölümündeki uyarıyı yinelemekte fayda var:

> **Uyarı**
> 
> 🚨 Bu paket vergiye tabi olan belge oluşturur, hiç bir sorumluluk kabul edilmez ve ne yaptığınızdan emin olana kadar debugMode açık şekilde test verileriyle işlem yapmanız önerilir.

**Comment by sercanaydin** [comment]
Merhaba Hocam,

Diğer issue.ları incelerken benzer bir problemi gördüm henüz denemedim ama eksik kısım bu olabilir. Ben sms doğrulaması yaparken faturayı aşağıdaki gibi set etmedim.
$oldInvoice = new Invoice(); $oldInvoice->setUuid("e8277cfa-4ac9-11ea-a5b5-acde48001122"); $client->setInvoice($oldInvoice)->getInvoiceFromAPI();

Sadece uuid ve operasyon id ile verifySMSCode methodunu çalıştırdım. Akşama deneyebileceğim. Sorun buradan da kaynaklanıyor olabilir.

**Comment by sercanaydin** [comment]
Malesef bu şekilde de doğrulama yapamadım. SMS geliyor doğruluyorum sonuç true dönüyor ancak GİB'den baktığımda onaylanmamış görüyorum.

**Comment by muratcesmecioglu** [comment]
Tekrar merhaba
1.9.4 sürümü yayınlandı. SMS onay kısmı ile ilgili bazı değişen yerler var. Tekrar deneyebilir misiniz?

Ben imzalama ve sms onayını test etmek için basit bir sayfa yazdım. Aşağıdaki linkten inceleyebilirsiniz.
https://gist.github.com/muratcesmecioglu/a37c1b9ca843d0117f2b3bd3cb02cc14

**Comment by agvanet** [comment]
Sms mesajı geliyor, onaylandı diye cevap dönüyor ama GİB'de onaylanmamış olarak görülmeye devam ediyor.

> Tekrar merhaba 1.9.4 sürümü yayınlandı. SMS onay kısmı ile ilgili bazı değişen yerler var. Tekrar deneyebilir misiniz?
> 
> Ben imzalama ve sms onayını test etmek için basit bir sayfa yazdım. Aşağıdaki linkten inceleyebilirsiniz. https://gist.github.com/muratcesmecioglu/a37c1b9ca843d0117f2b3bd3cb02cc14

Sms mesajı geliyor, onaylandı diye cevap dönüyor ama GİB'de onaylanmamış olarak görülmeye devam ediyor.

**Comment by serkandiker** [comment]
"SIFRE" => $sms_code,
                "OID" => $operation_id,
				"OPR" => 1,
				'DATA' => [$draft_invoice]
onay fonksiyonu içindeki DATA değişkeni içine onay için seçtiğiniz uuid ekleyerek onaylayabilirsiniz .olumlu cevap almanız normal çünkü oid ve şifre eşleşiyor.Sms sistemi ve fatura sistemi iki ayrı sistem

**Comment by muratcesmecioglu** [comment]
> Sms mesajı geliyor, onaylandı diye cevap dönüyor ama GİB'de onaylanmamış olarak görülmeye devam ediyor.
> 
> > Tekrar merhaba 1.9.4 sürümü yayınlandı. SMS onay kısmı ile ilgili bazı değişen yerler var. Tekrar deneyebilir misiniz?
> > Ben imzalama ve sms onayını test etmek için basit bir sayfa yazdım. Aşağıdaki linkten inceleyebilirsiniz. https://gist.github.com/muratcesmecioglu/a37c1b9ca843d0117f2b3bd3cb02cc14
> 
> Sms mesajı geliyor, onaylandı diye cevap dönüyor ama GİB'de onaylanmamış olarak görülmeye devam ediyor.

Sormak zorundayım ama; sms onayından sonra tekrar getInvoicesFromAPI ile yeni bir sorgulama yapıyorsunuz değil mi? Portal üzerinden de imzalasanız alttaki bölümün güncellenmesi için tekrar sorgulama yapmak gerekiyor biliyorsunuz.
---
Dün verdiğim kodlar ile oluşturduğum bir faturayı onayladım. Bir sonraki faturamda tekrar deneyeceğim.

**Comment by agvanet** [comment]
Evet onayladıktan sonra tekrar getInvoicesFromAPI  ile sorgulama yapıyorum ama onaylanmamış oluyor.

**Comment by muratcesmecioglu** [comment]
Tekrar merhaba.
Yoğunluktan yanlış kodları paylaşmışım. Hatta dosya adını bile py (python) olarak yazmışım :)

https://gist.github.com/muratcesmecioglu/a37c1b9ca843d0117f2b3bd3cb02cc14

Şu kodlar ile deneyebilir misiniz?

**Comment by agvanet** [comment]
Malesef yine Onaylandı mesajını alıyorum ama onaylanmamış olarak kalıyor.

**Comment by muratcesmecioglu** [comment]
> Malesef yine Onaylandı mesajını alıyorum ama onaylanmamış olarak kalıyor.

Bana e-posta atabilir misiniz:  kullanıcı adım (at) gmail nokta kom
