### ISSUE TITLE
ramsey/uuid 2.9 

### ISSUE THREAD

**Issue by FatihSafa** [furkankadioglu/efatura#6]
Hocam Merhabalar,

Öncelikle paylaşımınız için çok teşekkürler. Laravel içerisine kurmaya çalıştığımda ramsey/uuid 2.9 sürümünü kuramıyor. bu nedenle projeme dahil edemiyorum. bununla alakalı bir güncelleme yapma durumunuz olur mu veya bu konuda farklı türden öneriniz varsa yardımcı olursanız çok memnun olurum. Şimdiden teşekkürler...

**Comment by furkankadioglu** [comment]
Merhaba, tam olarak neden olmadığı hakkında bir bilgi verebilir misiniz?

**Comment by FatihSafa** [comment]
Durumdan benim anladığım ramsey/uuid 2.9 sürümü Laravel ile uyuşmuyor. Direk kurmak istediğimde de 2.9 kurdurmuyor. Aldığım hata aşağıdaki şekildedir. 

 

> Problem 1
>     - Installation request for ramsey/uuid (locked at 4.0.1) -> satisfiable by ramsey/uuid[4.0.1].
>     - furkankadioglu/efatura 1.7.1 requires ramsey/uuid ^2.9 -> satisfiable by ramsey/uuid[2.9.0].
>     - furkankadioglu/efatura 1.7.2 requires ramsey/uuid ^2.9 -> satisfiable by ramsey/uuid[2.9.0].
>     - **Conclusion: don't install ramsey/uuid 2.9.0**
>     - Installation request for furkankadioglu/efatura ^1.7 -> satisfiable by furkankadioglu/efatura[1.7.1, 1.7.2].

**Comment by ahmeti** [comment]
Merhaba Fatih ve Furkan,

Bunun nedeni; ne yazık ki Ramsey'in paket namespace'ini güncellemesi.

2.x verisonlarda "Rhumsaa\Uuid" namespace sahipken, 3.x versiyonlarda "Ramsey\Uuid" namespace'i kullanmaya başladı.

Ramsey 2.x
https://github.com/ramsey/uuid/blob/2.0.0/composer.json#L34

Ramsey 3.x
https://github.com/ramsey/uuid/blob/3.0.0/composer.json#L46

Ben de Laravel ile çalıştırdığım için paketi forklayıp, composer.json bağımlılıklarında ^3.7 versiyonunu kullandım. Namespace'i güncelledim. Kusursuz bir şekilde çalıştı.

**Comment by furkankadioglu** [comment]
@ahmeti @FatihSafa İlginize çok teşekkür ederim.

Forku da inceleyip en geç pazartesiye kadar uyumluluğu sağlamış olacağım.

**Comment by furkankadioglu** [comment]
Sorun çözüldü, Laravel 7.X ile denediğim kadarıyla bir problem gözükmüyor. 6 veya 5 ile denemedim ama sorun çıkacağını sanmıyorum. 

Bildirdiğiniz için ayrıca teşekkür ederim. 👍
