### ISSUE TITLE
E-Arşive Erişim Sağlama

### ISSUE THREAD

**Issue by fatihkiziltoprak** [furkankadioglu/efatura#61]
Merhaba

Öncelikle kodlar için teşekkür ederim. Aşağıda birkaç sorum bulunuyor cevaplarsanız çok mutlu olurum.

1) Kendimin şahıs firması var ve e-arşiv portalını aktif olarak kullanıyorum. Her zaman girdiğim kullanıcı ve şifre yeterlimidir.
2) Test kullanıcısını nasıl alabilirim.
3) Bu api unofficial bir apidir. 

Teşekkür ederim.
İyi çalışmalar

**Comment by muratcesmecioglu** [comment]
1. Evet, Portala girişte kullandığınız kullanıcı adı ve şifre yeterlidir.
2. Test kullanıcısını `$client->setDebugMode(true)->setTestCredentials();` ile alabilirsiniz.
3. Bu, e-arşiv portala bağlanıp fatura oluşturmak, düzenlemek, onaylamak ve adınıza kesilen faturaları görebilmek gibi işlemleri yapabileceğiniz resmi olmayan bir kütüphanedir. Bu kütüphaneyi kullanarak fatura kesen, düzenleyen, onaylayan bir sistem yazabilirsiniz.

**Comment by fatihkiziltoprak** [comment]
Tamamdır. Tekrar çok teşekkür ederim.
