### ISSUE TITLE
Mali Mühürle Çalışır mı?

### ISSUE THREAD

**Issue by sauronntrr** [furkankadioglu/efatura#62]
Arkadaşlar daha önce de sormuştum kusura bakmayın ama paket çok güzel çalışıyor. Normal entegratörden daha iyi valla. Mali mühür var, efatura mükellefiyim bunu kullanamam değil mi?

**Comment by muratcesmecioglu** [comment]
Efatura mükellefi iseniz faturayı efatura portalından veya entegratör üzerinden kesmeniz gerekiyor. Bu kütüphane sadece earşiv içindir.

**Comment by sauronntrr** [comment]
Çok üzüldüm ya... Teşekkür ederim cevabınız için.
