### ISSUE TITLE
Tarih Aralığı Fatura Listeletme

### ISSUE THREAD

**Issue by PremiumTurk** [furkankadioglu/efatura#8]
$client->getInvoicesFromAPI("01/01/2020", "19/05/2020") fonksiyonu kendi içerisinde çalışmıyor. InvoiceManager.php'ye de baktım fakat ekrana bir hata yazdırmıyor ve kendinden sonraki satırları da çalıştırmıyor. Ör; https://prnt.sc/sk8wue görselinde koddan sonraki test yazısı ve devamındaki kodlar çalışmıyor. Php uyumluluğu vb olabilir mi? Sıfırdan güncel şekilde şuan kurulum yaptım. PHP Sürüm; 7.2.24

**Comment by PremiumTurk** [comment]
Amsterdamdaki sunucudan fransadaki sunucuya aktardığımda burda centos panelden dolayı galiba hata ayıklaması yapabildi. Sunucu değiştirmem rağmen hata var yani hata görseli; https://prnt.sc/skelsg

**Comment by PremiumTurk** [comment]
Yeni bir veri eklemesi daha; "body" değişkenini açtığımda çıkan hata; https://prnt.sc/skeo6t

**Comment by furkankadioglu** [comment]
E-Arşiv API'ı versiyon güncellemeden direk mevcut API sistemine ekstra zorunlu parametreler eklemişler. Bu nedenle bizim sistemimiz patlamış. hangiTip diye bir değişkenin eklenmesi gerekiyordu. Şimdilik hard coded ancak onu da değiştireceğiz.

Sorun yeni güncellemeyle çözülmüş olmalı, bildirdiğin için çok teşekkürler @PremiumTurk
