### ISSUE TITLE
Fatura oluşturmaya çalıştıktan sonraki geri bildirimdeki değişiklik ( throw Fatura Oluşturulmadı )

### ISSUE THREAD

**Issue by tarkantoan** [furkankadioglu/efatura#83]
![image](https://user-images.githubusercontent.com/47943807/172125090-0fc81e58-9712-48b0-a5e9-61c2ffd53e91.png)

**Comment by muratcesmecioglu** [comment]
Merhaba. Sanırım kütüphanenin eski bir versiyonunu kullanıyorsunuz.
Mevcut sürümde bu değişiklik daha önce düzeltildi.
https://github.com/furkankadioglu/efatura/blob/master/src/InvoiceManager.php#L494

**Comment by tarkantoan** [comment]
Evet haklısınız son sürüm kullandığımdan oldukça emindim.  :)
