### ISSUE TITLE
Fatura Oluşturulamadı - Form parametrelerinde hata var.

### ISSUE THREAD

**Issue by PremiumTurk** [furkankadioglu/efatura#9]
- Hiçbir parametreyi değiştirmedim fakat test kullanıcıda fatura oluştururken hata veriyor. 
- invoicemanager.php dosyasında "body" değişkenindeki "data" dizisi Form parametrelerinde hata var uyarısı 
- veriyor. .php dosyasında 451. satırda hata. 451. satıra prameters değişkenini dizi halinde ekrana yazdırıyorum görseldeki gibi fakat içerikte türkçe karkater dışında bir fark görülmüyor gibi. 

Ekran görüntüsü; https://prnt.sc/skexn3

**Comment by muratcesmecioglu** [comment]
Gib tarafında değişiklik söz konusu. Yeni eklenen parametre var. Ayrıca başarılı mesajı dönüşü değişmiş.

**Comment by PremiumTurk** [comment]
Hmm anladım yazılıma güncelleme gelecek mi peki composer üzerinden ?

**Comment by furkankadioglu** [comment]
Merhaba, 

İncelemeye başladım. En kısa sürede haber vereceğim. Güncelleme en kısa sürede gelecek.

**Comment by muratcesmecioglu** [comment]
@furkankadioglu Şu #10 PR'ı kontrol edebilir misin?

**Comment by PremiumTurk** [comment]
Tesekkurler @muratcesmecioglu düzenlemeleri uyguladığımda halloldu.

**Comment by furkankadioglu** [comment]
Eline sağlık @muratcesmecioglu 

Pull requesti mergeledim. Şu an herşey yolunda gibi duruyor. İyi çalışmalar :)
