### ISSUE TITLE
Yabancı Para Birimi Cinsinden Fatura Kesilebiliyor Mu?

### ISSUE THREAD

**Issue by blackhawktr** [furkankadioglu/efatura#92]
Merhaba,
EUR cinsinden fatura keserken Fatura Oluşturulamadı hatası veriyor. Gözden kaçırdığım bir yer yok gibi. VKN 10 tane 2 olacak şekilde yabancı para birimiyle fatura oluşturabilen oldu mu acaba?

**Comment by furkankadioglu** [comment]
Ben hep yabancı para birimiyle deniyorum aslında, **tests** klasörü size bu konuda yardımcı olabilir. Muhtemelen bir yeri atlıyorsunuz. Örneği veya hatayı paylaşırsanız daha kolay yardımcı olabilir topluluk.
