### ISSUE TITLE
Bad Request 400 Hatası

### ISSUE THREAD

**Issue by erenn44** [furkankadioglu/efatura#98]
Üstadlar bir kaç gündür tüm ekranlarda ilgili hatayı almaktayız. İlgili hata konusunda çözüm üretebilen oldu mu?

**Comment by metin71** [comment]
çözebildin mi hocam sorunu.??

**Comment by erenn44** [comment]
yok ben henüz çözüm bulamadım15.09.2022, 14:05, "metin71" ***@***.***>:
çözebildin mi hocam sorunu.??

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- ------------------SaygılarımlaEren Şengün

**Comment by ztemet** [comment]
> Sistem bende çalışıyor. Sorgu yaptığınız ip güvenlik duvarına takılıyor olabilir farklı bir ipden deneyebilir isiniz.

İbrahim hocam denedim bir türlü olmuyor client error hatası loglarda var. Son bir kaç haftadır böyle ondan önce problemsizdi

**Comment by ztemet** [comment]
> Sistem bende çalışıyor. Sorgu yaptığınız ip güvenlik duvarına takılıyor olabilir farklı bir ipden deneyebilir isiniz.

"PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://earsivportaltest.efatura.gov.tr/earsiv-services/esign` resulted in a `400 Bad Request` response:
<html><head><title>Error</title></head><body>
<h2>ERROR: </h2>
<br>
</body></html>

**Comment by metin71** [comment]
varmı bir çözüm yolu bulan yada başka şekilde çalıştıran...

**Comment by metin71** [comment]
arkadaşlar sorun kodlardan değil ip adresinin kara listeye alınması ile alakalıdır. aşağıdaki adresten sunucu ip adresini kontrol edip kara listede görünüyorsa talep açın düzeltince sorun kalmıyor.

https://www.brightcloud.com/tools/url-ip-lookup.php

**Comment by erenn44** [comment]
> arkadaşlar sorun kodlardan değil ip adresinin kara listeye alınması ile alakalıdır. aşağıdaki adresten sunucu ip adresini kontrol edip kara listede görünüyorsa talep açın düzeltince sorun kalmıyor.
> 
> https://www.brightcloud.com/tools/url-ip-lookup.php

Nereye talep açıyoruz Üstad biraz açsanız

**Comment by metin71** [comment]
![image](https://user-images.githubusercontent.com/78187072/193347057-01b94041-bfb5-4724-ae57-eda4ef50c1d1.png)

sol üst kısımda ip adresini sorgulama yapın sağ tarafta çarpı işareti görüyorsanız..  sol alt kısımdaki formu doldurup gönderin 2 gün içinde inceleyip bilgi veriyorlar..

**Comment by erenn44** [comment]
> ![image](https://user-images.githubusercontent.com/78187072/193347057-01b94041-bfb5-4724-ae57-eda4ef50c1d1.png)
> 
> sol üst kısımda ip adresini sorgulama yapın sağ tarafta çarpı işareti görüyorsanız.. sol alt kısımdaki formu doldurup gönderin 2 gün içinde inceleyip bilgi veriyorlar..

bu şekilde benimde sorunum çözülmüştür. Teşekkür ederim.
